# admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ2MDc3Mjl9.IE9uQUOHYgHhgjvQgXngtPtg0rHVbMI7GokFtci1LBY

### Spiders Index
GET http://localhost:3000/spiders.json

### Spiders Create
POST http://localhost:3000/spiders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ2MDc3Mjl9.IE9uQUOHYgHhgjvQgXngtPtg0rHVbMI7GokFtci1LBY
Content-Type: application/json

{
  "name": "Aunt May", 
  "age": 150,
  "arch_nemesis": "Shingles"
}


### Spiders Show
GET http://localhost:3000/spiders/3.json


### Spiders Update
PATCH http://localhost:3000/spiders/4.json
Content-Type: application/json

{
  "arch_nemesis": "wrinkles"
}

### Spiders Destroy
DELETE http://localhost:3000/spiders/4.json



### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@test.com",
  "password" : "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}